### ISSUE TITLE
Create Concept Art

### ISSUE THREAD

**Issue by Rojuinex** [nterry/AS3RG#6]

**Comment by ghost** [comment]
Looks like we got some concept art from Nick on the GDrive. I will just put this into testing state until we all can agree on the look.

**Comment by Rojuinex** [comment]
Was this for school?  Can I close this issue?

**Comment by skylerh** [comment]
Yes, This was for school. I'm not using it anymore

**Comment by jwalk165** [comment]
Yeah, go ahead and close that.
